class_name HotelPropSpawner
extends RefCounted


# One CRT computer terminal per floor (every floor except 1 - empty_box_mode returns out of
# _build_floor_geometry before this ever runs - and the roof, generated by a wholly separate
# function). Reads out one of the log entries from LORE.md's "Текстовые логи в CRT-терминалах"
# on interact (crt_terminal.gd) - a real, if simple, payoff for content that existed in the lore
# doc but was never actually reachable in-game.
#
# Anchored to DoubleRoom orig_num 406 (z=10.0, never mirrored - see HotelConstants.DOUBLE_ROOM_LAYOUT), which
# exists identically on every floor, mounted flush against the OUTSIDE (corridor-facing) surface
# of that room's own RoomEastWall (local X=4.8, size.x=0.2 -> outer face at local X=4.9) so it
# stands in the corridor without touching the wall's own geometry at all - no CSG, no risk of the
# "whole combined shape vanishes" fragility that's bitten this project before. Placed at local
# Z=2.0 (room spans Z 0..10), well clear of that room's own RoomDoorHole at Z=8.5.
static func add_floor_terminal(parent: Node, f_scale: float, at: Vector3 = Vector3.INF, rot_y: float = 0.0) -> void:
	# X=5.05 = wall's own outer face (4.9) + half the casing's depth (0.14) - so the casing's
	# BACK sits flush against the wall instead of embedded inside it or floating in mid-corridor.
	var room_world = Vector3(HotelConstants.DOUBLE_ROOM_BASE_X, 0, 10.0) * f_scale
	var local_offset = Vector3(5.05, 1.3, 2.0) * f_scale
	var terminal_pos = room_world + local_offset
	if at != Vector3.INF:
		terminal_pos = at * f_scale # the lab's terminal: an explicit spot instead of the corridor one

	var terminal = Area3D.new()
	terminal.name = "CrtTerminal"
	terminal.collision_layer = 4 # same layer vhs_tape.tscn uses - matches the interact raycast/proximity mask
	terminal.collision_mask = 0
	terminal.set_script(load("res://scripts/interactables/crt_terminal.gd"))
	terminal.position = terminal_pos
	terminal.rotation.y = rot_y

	var coll = CollisionShape3D.new()
	var shape = BoxShape3D.new()
	shape.size = Vector3(0.3, 0.4, 0.5) * f_scale
	coll.shape = shape
	terminal.add_child(coll)

	# Beige plastic casing - period-accurate for a Soviet-era terminal, distinct from the dark
	# gunmetal used everywhere else (robot, wardrobe) so it reads as "old computer", not "machine".
	var casing_mat = StandardMaterial3D.new()
	casing_mat.albedo_color = Color(0.72, 0.68, 0.56)
	casing_mat.roughness = 0.7
	var casing = MeshInstance3D.new()
	var casing_mesh = BoxMesh.new()
	casing_mesh.size = Vector3(0.28, 0.35, 0.4) * f_scale
	casing_mesh.material = casing_mat
	casing.mesh = casing_mesh
	terminal.add_child(casing)

	# Recessed monochrome-green screen, glowing regardless of room lighting - the classic look
	# for text-only computer terminals of this era, and a color no other emissive element in the
	# hotel currently uses (holograms are cyan, the robot's eye is red, hazard tape is yellow).
	var screen_mat = StandardMaterial3D.new()
	screen_mat.albedo_color = Color(0.05, 0.25, 0.08)
	screen_mat.emission_enabled = true
	screen_mat.emission = Color(0.15, 0.9, 0.3)
	screen_mat.emission_energy_multiplier = 1.5
	var screen = MeshInstance3D.new()
	var screen_mesh = BoxMesh.new()
	screen_mesh.size = Vector3(0.02, 0.22, 0.28) * f_scale
	screen_mesh.material = screen_mat
	screen.position = Vector3(0.13, 0.0, 0.0) * f_scale
	screen.mesh = screen_mesh
	terminal.add_child(screen)

	parent.add_child(terminal)


static func find_props(node: Node, prop_name: String, arr: Array) -> void:
	if node.name.begins_with(prop_name):
		arr.append(node)
	for child in node.get_children():
		find_props(child, prop_name, arr)


# Per LORE.md, Cassette #1 ("Личность") is found in the starting room's furniture and
# Cassette #2 ("Инцидент") is nearby in the corridor - both close to where the player actually
# appears. The player spawns at the same world (X=0, Z=0) on every floor (see _move_player()),
# so "closest to spawn" is a stand-in for "in/near the starting room" that works on any floor,
# not just the one the player happens to be reading this on.
static func closest_to_spawn(props: Array) -> Node:
	var closest: Node = null
	var closest_dist_sq = INF
	for p in props:
		var pos = p.global_position
		var dist_sq = pos.x * pos.x + pos.z * pos.z
		if dist_sq < closest_dist_sq:
			closest_dist_sq = dist_sq
			closest = p
	return closest


# Used for cassette placement on every floor except 4 (see spawn_cassettes_other_floor()) -
# those floors have no "closest to spawn" relationship to preserve, so a genuinely random pick
# keeps their layout from being predictable across floors.
static func random_from(props: Array) -> Node:
	if props.is_empty():
		return null
	return props[randi() % props.size()]


static func spawn_cassettes_start_floor(parent: Node, f_scale: float, scene: PackedScene) -> void:
	var wardrobes = []
	find_props(parent, "Wardrobe", wardrobes)
	var chosen_wardrobe = closest_to_spawn(wardrobes)

	# Excludes tables in the wardrobe's own room before picking the closest one - every room has
	# both a wardrobe and a table, so without this the globally-closest table is almost always in
	# the SAME room as the globally-closest wardrobe (that room being closest to spawn is exactly
	# why it got picked as the starting room in the first place), landing both Cassette #1 and #2
	# on top of each other in the player's own starting room instead of two separate ones.
	var tables = []
	find_props(parent, "Table", tables)
	if chosen_wardrobe != null:
		var wardrobe_room = chosen_wardrobe.get_parent()
		tables = tables.filter(func(t): return t.get_parent() != wardrobe_room)
	var chosen_table = closest_to_spawn(tables)

	if parent.name == "GeneratedFloor_Main":
		print("[generator] _spawn_cassettes on ", parent.name, ": wardrobes found=", wardrobes.size(),
			" chosen=", (chosen_wardrobe.get_path() if chosen_wardrobe else "NONE"),
			" | tables found=", tables.size(),
			" chosen=", (chosen_table.get_path() if chosen_table else "NONE"))

	for i in range(3):
		var inst = scene.instantiate()
		inst.name = "Cassette_" + str(i)
		# Without this, every cassette keeps vhs_tape.gd's @export default (tape_id=0) - all 3
		# would collect as the same id, so GameStateManager.tapes_found (a Set keyed by id) never
		# grows past size 1, all_tapes_collected never fires,
		# and every cassette narrates tape #1's text regardless of which one was picked up.
		inst.tape_id = i

		# inst has no parent yet, so its OWN global_transform/global_position are unreliable
		# (Godot only tracks a node's global transform correctly once it's actually inside the
		# tree - writing/reading them on an orphan silently behaves as if its position were
		# zero, which is exactly what put cassettes near world origin/the corridor instead of
		# on the chosen furniture). chosen_wardrobe/chosen_table themselves ARE already in the
		# tree, so reading THEIR global_transform is fine - the fix is to convert that world-
		# space target into parent-relative LOCAL coordinates and assign inst.transform
		# (not inst.global_transform) before add_child(), the same pattern used everywhere
		# else in this generator.
		if i == 0 and chosen_wardrobe != null:
			inst.location_hint = "tape_hint_start_wardrobe"
			var target = chosen_wardrobe.global_transform
			# X=-0.28 matches the shelf zone's center in wardrobe.tscn (the other half of the
			# interior is now an open hanging compartment with a rod, not a shelf).
			target.origin += chosen_wardrobe.global_basis * Vector3(-0.28, 1.15, 0.05)
			inst.transform = parent.global_transform.affine_inverse() * target
		elif i == 1 and chosen_table != null:
			inst.location_hint = "tape_hint_table"
			var target = chosen_table.global_transform
			target.origin += chosen_table.global_basis * Vector3(0.0, 0.8, 0.0)
			inst.transform = parent.global_transform.affine_inverse() * target
		elif i == 2:
			inst.location_hint = "tape_hint_lift"
			inst.position = Vector3(7.2 * f_scale, 0.05 * f_scale, -23.5 * f_scale)
			inst.rotation.y = randf_range(0, PI * 2)
		else:
			var rand_x = randf_range(-2.0, 4.0)
			var rand_z = randf_range(-20.0, 40.0)
			inst.position = Vector3(rand_x * f_scale, 0.5 * f_scale, rand_z * f_scale)
			inst.rotation.y = randf_range(0, PI * 2)

		parent.add_child(inst)
		if parent.name == "GeneratedFloor_Main":
			print("[generator] Cassette_", i, " global_position=", inst.global_position)


# Every floor except 4 (see HotelPropSpawner.spawn_cassettes()): one cassette on a table in a random room, one in
# the maintenance room, one in a wardrobe in a random room - none of floor 4's "closest to spawn"
# logic applies since the player doesn't start on these floors.
static func spawn_cassettes_other_floor(parent: Node, f_scale: float, scene: PackedScene) -> void:
	# Floor 5 has one room sealed off from the corridor (HotelTrapBuilder.add_room_shuffle_trap()) - the wardrobe
	# tape goes there, and the table tape anywhere else.
	var sealed_room = parent.get_meta("sealed_room") if parent.has_meta("sealed_room") else null

	var tables = []
	find_props(parent, "Table", tables)
	if sealed_room != null:
		tables = tables.filter(func(t): return t.get_parent() != sealed_room)
	var chosen_table = random_from(tables)

	# Excludes the table's own room before picking the wardrobe - same reasoning as
	# spawn_cassettes_start_floor()'s wardrobe/table split: every room has both, so without this
	# the two could easily land in the same room by pure chance.
	var wardrobes = []
	find_props(parent, "Wardrobe", wardrobes)
	if chosen_table != null:
		var table_room = chosen_table.get_parent()
		wardrobes = wardrobes.filter(func(w): return w.get_parent() != table_room)
	var chosen_wardrobe = random_from(wardrobes)
	if sealed_room != null:
		chosen_wardrobe = sealed_room.get_node_or_null("Wardrobe")

	# Floor 8 lets the hero into one room only, his own (HotelTrapBuilder.add_name_doors()) - both room tapes
	# go there, on its table and in its wardrobe.
	var own_room = parent.get_meta("own_room") if parent.has_meta("own_room") else null
	if own_room != null:
		var own_tables = []
		find_props(own_room, "Table", own_tables)
		chosen_table = own_tables[0] if not own_tables.is_empty() else chosen_table
		chosen_wardrobe = own_room.get_node_or_null("Wardrobe")

	# find_props() only matches nodes named "Wardrobe" - the maintenance room's own two
	# ("MaintWardrobe1"/"MaintWardrobe2", see HotelBlockBuilder.generate_maintenance_room()) don't match that
	# prefix, so they're never candidates for chosen_wardrobe above; used here instead as the
	# actual "in the maintenance room" spot.
	var maint_wardrobe = parent.get_node_or_null("MaintWardrobe1")

	for i in range(3):
		var inst = scene.instantiate()
		inst.name = "Cassette_" + str(i)
		inst.tape_id = i

		# See spawn_cassettes_start_floor() for why position must be set via a parent-relative
		# LOCAL transform (converted from the target's global_transform) before add_child().
		if i == 0 and chosen_table != null:
			inst.location_hint = "tape_hint_own_room" if own_room != null else "tape_hint_table"
			var target = chosen_table.global_transform
			target.origin += chosen_table.global_basis * Vector3(0.0, 0.8, 0.0)
			inst.transform = parent.global_transform.affine_inverse() * target
		elif i == 1 and maint_wardrobe != null:
			inst.location_hint = "tape_hint_maintenance"
			var target = maint_wardrobe.global_transform
			target.origin += maint_wardrobe.global_basis * Vector3(-0.28, 1.15, 0.05)
			inst.transform = parent.global_transform.affine_inverse() * target
		elif i == 2 and chosen_wardrobe != null:
			inst.location_hint = "tape_hint_sealed" if sealed_room != null else ("tape_hint_own_room" if own_room != null else "tape_hint_wardrobe")
			var target = chosen_wardrobe.global_transform
			target.origin += chosen_wardrobe.global_basis * Vector3(-0.28, 1.15, 0.05)
			inst.transform = parent.global_transform.affine_inverse() * target
		else:
			# Fallback if a floor is somehow missing one of the three spots (shouldn't happen -
			# every floor generates the same room/maintenance layout).
			var rand_x = randf_range(-2.0, 4.0)
			var rand_z = randf_range(-20.0, 40.0)
			inst.position = Vector3(rand_x * f_scale, 0.5 * f_scale, rand_z * f_scale)
			inst.rotation.y = randf_range(0, PI * 2)

		parent.add_child(inst)


# Floor 6's nightmare - see sleeper_cerberus.gd for the rule. Four of them stand along the main
# corridor, alternating sides so none blocks the way. Corridor only, on purpose: a sleeper shut
# inside a room could never be lured away from it (closed doors are solid to the navmesh), so
# taking a tape there would be a guaranteed catch instead of a decision.
const SLEEPER_POSTS: Array = [Vector2(-0.6, -16.0), Vector2(2.8, -5.0), Vector2(-0.6, 7.0), Vector2(2.8, 19.0)] # X, Z

static func spawn_sleepers(parent: Node3D, f_scale: float, off_flag: StringName) -> void:
	var scene = load("res://entities/enemies/cerberus/cerberus.tscn")
	var sleeper_script = load("res://scripts/enemies/sleeper_cerberus.gd")
	if not scene or not sleeper_script: return
	for i in range(HotelPropSpawner.SLEEPER_POSTS.size()):
		var post: Vector2 = HotelPropSpawner.SLEEPER_POSTS[i]
		var inst = scene.instantiate()
		inst.set_script(sleeper_script)
		inst.name = "Sleeper_" + str(i + 1)
		inst.off_flag = off_flag
		# position MUST be set before add_child() - see HotelBlockBuilder.generate_maintenance_room() for why.
		inst.position = Vector3(post.x * f_scale, 0, post.y * f_scale)
		inst.rotation.y = PI / 2.0 if post.x < 1.0 else -PI / 2.0 # backs to the wall, facing across
		# Where one of them puts a caught player: the open corridor in front of this floor's
		# elevator door (elevator at HotelConstants.ELEVATOR_CENTER_X, its door on the Z=-25 face).
		inst.return_position = parent.global_position + Vector3(HotelConstants.ELEVATOR_CENTER_X * f_scale, 0.1, (HotelConstants.ELEVATOR_CENTER_Z + 2.0) * f_scale)
		parent.add_child(inst)



static func spawn_cassettes(parent: Node, f_scale: float, f_num: int) -> void:
	var scene = load("res://entities/interactables/vhs_tape.tscn")
	if not scene: return

	# Floor 4 is the player's starting floor - Cassette #1 ("Личность") always sits in the same
	# room the player spawns in (see _move_player()), which relies on "closest wardrobe/table to
	# world origin" specifically. Every other floor has no such spawn-point relationship, so it
	# gets a simpler, fully-random layout instead (table/maintenance-room/wardrobe - see
	# HotelPropSpawner.spawn_cassettes_other_floor()).
	if f_num == 4:
		spawn_cassettes_start_floor(parent, f_scale, scene)
	else:
		spawn_cassettes_other_floor(parent, f_scale, scene)

static func spawn_cerberus(parent: Node, f_scale: float) -> void:
	var scene = load("res://entities/enemies/cerberus/cerberus.tscn")
	if not scene: return
	var inst = scene.instantiate()
	inst.name = "Cerberus"
	# position MUST be set before add_child() - see HotelBlockBuilder.generate_maintenance_room() for why.
	inst.position = Vector3(1.0 * f_scale, 0, 10.0 * f_scale)

	# cerberus_ai.gd starts in State.IDLE and only ever leaves it for State.PATROL if
	# patrol_points is non-empty - left empty (the default), a spawned robot just stands at this
	# exact spot forever, only reacting if the player happens to wander into its 12m
	# DetectionArea. Two Marker3D points give it a back-and-forth patrol instead of standing
	# frozen - spanning the full central corridor (Z ~[-25.18, 25.0], see z_main_len/z_main_pos
	# in _build_floor_geometry, inset 1.2m from each end wall) rather than just a few meters
	# around the spawn point, so it actually walks the length of the hallway it's guarding.
	# Positions are LOCAL to inst (which isn't in the tree yet), so they're offsets from its own
	# origin (spawned at local Z=10.0), not world/parent coordinates.
	var patrol_a = Marker3D.new()
	patrol_a.position = Vector3(0, 0, (-24.0 - 10.0) * f_scale)
	inst.add_child(patrol_a)
	var patrol_b = Marker3D.new()
	patrol_b.position = Vector3(0, 0, (24.0 - 10.0) * f_scale)
	inst.add_child(patrol_b)
	# Typed on purpose: patrol_points is Array[Marker3D], and assigning a plain untyped Array to
	# it is a script error that aborts this function before add_child() below - which is why no
	# generated floor actually had its robot.
	var patrol_points: Array[Marker3D] = [patrol_a, patrol_b]
	inst.patrol_points = patrol_points

	parent.add_child(inst)

